apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    type: myapp
spec:
  template:
    metadata:
      name: fe-nginx
      labels:
        type: FE
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
  replicas: 2


