apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    type: myapp-rs
  name: fe
spec:
  selector:
    matchLabels:
      type: fe
  replicas: 2
  template:
    spec:
      containers:
        - name: nginx
          image: nginx
    metadata:
      name: fe
      labels:
        type: fe
